### ISSUE TITLE
Assorted To-Do List

### ISSUE THREAD

**Issue by dtannyc1** [dtannyc1/JS-Project#1]
- [x] Fix modal button hover moving everything around 
- [x] Game Setup should be Start Game?
- [x] Replace mute button, make it a toggle
  - Mute button should also mute sword sound effects
- [x] Fix perspective on arcade cabinet to match keyboard?
- [x] Add Wellfound Link
  - Links should open in a new tab
- [ ] Add glow effect behind arcade cabinet to make it stand out more
- [ ] Add additional art assets: extra backgrounds, extra characters
- [ ] Add animations to how to play menu - maybe add a controllable character?
- [ ] Refactor animations to true FPS system
